// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddICloudAccounts(arg1) {
  return window['go']['main']['App']['AddICloudAccounts'](arg1);
}

export function AddOutlookAccounts(arg1) {
  return window['go']['main']['App']['AddOutlookAccounts'](arg1);
}

export function AddProxyEntry(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddProxyEntry'](arg1, arg2, arg3);
}

export function CheckUpdate() {
  return window['go']['main']['App']['CheckUpdate']();
}

export function ClearICloudAccounts() {
  return window['go']['main']['App']['ClearICloudAccounts']();
}

export function ClearLogs() {
  return window['go']['main']['App']['ClearLogs']();
}

export function ClearOutlookAccounts() {
  return window['go']['main']['App']['ClearOutlookAccounts']();
}

export function ClearRegisteredOutlookAccounts() {
  return window['go']['main']['App']['ClearRegisteredOutlookAccounts']();
}

export function DeleteICloudAccount(arg1) {
  return window['go']['main']['App']['DeleteICloudAccount'](arg1);
}

export function DeleteOutlookAccount(arg1) {
  return window['go']['main']['App']['DeleteOutlookAccount'](arg1);
}

export function DeleteProxyEntry(arg1) {
  return window['go']['main']['App']['DeleteProxyEntry'](arg1);
}

export function GetAppSettings() {
  return window['go']['main']['App']['GetAppSettings']();
}

export function GetCloudMailConfigs() {
  return window['go']['main']['App']['GetCloudMailConfigs']();
}

export function GetCurrentVersion() {
  return window['go']['main']['App']['GetCurrentVersion']();
}

export function GetDataDir() {
  return window['go']['main']['App']['GetDataDir']();
}

export function GetICloudAccounts() {
  return window['go']['main']['App']['GetICloudAccounts']();
}

export function GetLanguage() {
  return window['go']['main']['App']['GetLanguage']();
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function GetMailNestConfig() {
  return window['go']['main']['App']['GetMailNestConfig']();
}

export function GetMoeMailConfigs() {
  return window['go']['main']['App']['GetMoeMailConfigs']();
}

export function GetOSLanguage() {
  return window['go']['main']['App']['GetOSLanguage']();
}

export function GetOutlookAccounts() {
  return window['go']['main']['App']['GetOutlookAccounts']();
}

export function GetResultOutputDir() {
  return window['go']['main']['App']['GetResultOutputDir']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function ImportICloudFile(arg1) {
  return window['go']['main']['App']['ImportICloudFile'](arg1);
}

export function ImportOutlookFile(arg1) {
  return window['go']['main']['App']['ImportOutlookFile'](arg1);
}

export function ListProxyPool() {
  return window['go']['main']['App']['ListProxyPool']();
}

export function OpenLogsDir() {
  return window['go']['main']['App']['OpenLogsDir']();
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function ResetDataDir() {
  return window['go']['main']['App']['ResetDataDir']();
}

export function ResetFingerprintCache() {
  return window['go']['main']['App']['ResetFingerprintCache']();
}

export function ResetResultOutputDir() {
  return window['go']['main']['App']['ResetResultOutputDir']();
}

export function SaveAppSettings(arg1) {
  return window['go']['main']['App']['SaveAppSettings'](arg1);
}

export function SaveCloudMailConfigs(arg1) {
  return window['go']['main']['App']['SaveCloudMailConfigs'](arg1);
}

export function SaveMailNestConfig(arg1) {
  return window['go']['main']['App']['SaveMailNestConfig'](arg1);
}

export function SaveMoeMailConfigs(arg1) {
  return window['go']['main']['App']['SaveMoeMailConfigs'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SelectICloudFile() {
  return window['go']['main']['App']['SelectICloudFile']();
}

export function SelectOutlookFile() {
  return window['go']['main']['App']['SelectOutlookFile']();
}

export function SetDataDir(arg1) {
  return window['go']['main']['App']['SetDataDir'](arg1);
}

export function SetResultOutputDir(arg1) {
  return window['go']['main']['App']['SetResultOutputDir'](arg1);
}

export function ShowDesktopNotification(arg1, arg2) {
  return window['go']['main']['App']['ShowDesktopNotification'](arg1, arg2);
}

export function StartTask(arg1) {
  return window['go']['main']['App']['StartTask'](arg1);
}

export function StopTask() {
  return window['go']['main']['App']['StopTask']();
}

export function TestCloudMailConnection(arg1) {
  return window['go']['main']['App']['TestCloudMailConnection'](arg1);
}

export function TestMailNestConnection(arg1) {
  return window['go']['main']['App']['TestMailNestConnection'](arg1);
}

export function TestMoeMailConnection(arg1) {
  return window['go']['main']['App']['TestMoeMailConnection'](arg1);
}

export function TestProxyByID(arg1) {
  return window['go']['main']['App']['TestProxyByID'](arg1);
}

export function UpdateProxyEntry(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UpdateProxyEntry'](arg1, arg2, arg3, arg4, arg5);
}
