// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {storage} from '../models';
import {email} from '../models';
import {proxy} from '../models';
import {task} from '../models';

export function AddICloudAccounts(arg1:string):Promise<Record<string, any>>;

export function AddOutlookAccounts(arg1:string):Promise<Record<string, any>>;

export function AddProxyEntry(arg1:string,arg2:string,arg3:number):Promise<Record<string, any>>;

export function CheckUpdate():Promise<Record<string, any>>;

export function ClearICloudAccounts():Promise<Record<string, any>>;

export function ClearLogs():Promise<Record<string, any>>;

export function ClearOutlookAccounts():Promise<Record<string, any>>;

export function ClearRegisteredOutlookAccounts():Promise<Record<string, any>>;

export function DeleteICloudAccount(arg1:string):Promise<Record<string, any>>;

export function DeleteOutlookAccount(arg1:string):Promise<Record<string, any>>;

export function DeleteProxyEntry(arg1:string):Promise<Record<string, any>>;

export function GetAppSettings():Promise<storage.AppSettings>;

export function GetCloudMailConfigs():Promise<Array<email.CloudMailConfig>>;

export function GetCurrentVersion():Promise<string>;

export function GetDataDir():Promise<string>;

export function GetICloudAccounts():Promise<Array<Record<string, any>>>;

export function GetLanguage():Promise<string>;

export function GetLogs():Promise<Array<string>>;

export function GetMailNestConfig():Promise<email.MailNestConfig>;

export function GetMoeMailConfigs():Promise<Array<email.MoeMailConfig>>;

export function GetOSLanguage():Promise<string>;

export function GetOutlookAccounts():Promise<Array<Record<string, any>>>;

export function GetResultOutputDir():Promise<string>;

export function GetStatus():Promise<Record<string, any>>;

export function ImportICloudFile(arg1:string):Promise<Record<string, any>>;

export function ImportOutlookFile(arg1:string):Promise<Record<string, any>>;

export function ListProxyPool():Promise<Array<proxy.PoolEntry>>;

export function OpenLogsDir():Promise<void>;

export function OpenURL(arg1:string):Promise<void>;

export function ResetDataDir():Promise<Record<string, any>>;

export function ResetFingerprintCache():Promise<Record<string, any>>;

export function ResetResultOutputDir():Promise<Record<string, any>>;

export function SaveAppSettings(arg1:storage.AppSettings):Promise<Record<string, any>>;

export function SaveCloudMailConfigs(arg1:string):Promise<Record<string, any>>;

export function SaveMailNestConfig(arg1:string):Promise<Record<string, any>>;

export function SaveMoeMailConfigs(arg1:string):Promise<Record<string, any>>;

export function SelectDirectory():Promise<string>;

export function SelectICloudFile():Promise<string>;

export function SelectOutlookFile():Promise<string>;

export function SetDataDir(arg1:string):Promise<Record<string, any>>;

export function SetResultOutputDir(arg1:string):Promise<Record<string, any>>;

export function ShowDesktopNotification(arg1:string,arg2:string):Promise<Record<string, any>>;

export function StartTask(arg1:task.StartTaskRequest):Promise<Record<string, any>>;

export function StopTask():Promise<Record<string, any>>;

export function TestCloudMailConnection(arg1:string):Promise<Record<string, any>>;

export function TestMailNestConnection(arg1:string):Promise<Record<string, any>>;

export function TestMoeMailConnection(arg1:string):Promise<Record<string, any>>;

export function TestProxyByID(arg1:string):Promise<Record<string, any>>;

export function UpdateProxyEntry(arg1:string,arg2:string,arg3:string,arg4:number,arg5:boolean):Promise<Record<string, any>>;
